CREATE TABLE IF NOT EXISTS `comments` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `url` TEXT NOT NULL,
  `nick` TEXT NOT NULL,
  `mail` TEXT NOT NULL,
  `link` TEXT,
  `comment` TEXT NOT NULL,
  `ua` TEXT,
  `ip` TEXT,
  `created` INTEGER NOT NULL,
  `rid` INTEGER DEFAULT 0,
  `pid` INTEGER DEFAULT 0,
  `isSpam` INTEGER DEFAULT 0,
  `status` INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS `counters` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `url` TEXT NOT NULL UNIQUE,
  `count` INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS `options` (
  `name` TEXT PRIMARY KEY,
  `value` TEXT
);

INSERT INTO `options` VALUES ('version', '1.6.21');
