#:schema node_modules/wrangler/config-schema.json
name = "cf-create-worker"
main = "src/index.js"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB" # available in your Worker on env.DB
database_name = "twikoo"
database_id = "0953c5e4-cffe-4dac-9067-6be815ef8e02"



[dev]
port = 5000
